---
inherit_from:
  - .rubocop-disables.yml
  - .rubocop-todo.yml

require:
  - rubocop-performance
  - rubocop-rubycw
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - 'tmp/**/*.rb'
    - 'vendor/**/*'
  NewCops: enable

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin
